### ISSUE TITLE
Rename Diffable children conformance to explicit type name `nestedChildren`

### ISSUE THREAD

**Issue by yikandel** [kandelvijaya/FastDiff#7]
Most user defined graph data structure uses `children` property to define nesting. 

Imagine what happens when user defined type:
```swift
struct View {
   var title: String 
   var children: [View]?
}
```
and when one uses `someView.children.compactMap` they might mean they want to use the `   var children: [View]?` property but it will call into `Diffable.children` requirement. 

Similarly; its impossible to conform to Diffable 

```swift
extension View: Diffable {
     var children: [View] {              // XXXX invalid redeclaration error by Xcode although the types are different by optionality. 
             return self.chilredn ?? []
     }
}
```

**Comment by kandelvijaya** [comment]
done.
